//
// Created by shawn on 3/18/22.
//

#ifndef TEENSY_CODE_ICM_STRUCT_H
#define TEENSY_CODE_ICM_STRUCT_H

#include "Sensor_struct.h"
#include <Adafruit_Sensor.h>
struct icm_struct: Sensor_struct {
    /**
     * Formatted string containing the temperature, acceleration, gyro info, and time info
     */
    String toString() override;
    /**
     * Returns CSV file header
     */
    String getHeader() const override;
    /**
     * Temperature of the sensor
     */
    float temperature{};
    /**
     * Gyroscope values from the sensor
     */
    float gyro[3]{};
    /**
     * Acceleration vector of the sensor in m/s/s
     */
    float acceleration[3]{};
    /**
     * Initializes an ICM data struct with data from the ICM sensor
     * @param icm_data Sensor events generated by the ICM Adafruit sensor
     */
    explicit icm_struct(sensors_event_t * icm_data);
    /**
     * Default constructor for the sensor
     */
    icm_struct() = default;
};


#endif //TEENSY_CODE_ICM_STRUCT_H
