//
// Created by shawn on 4/22/22.
//

#ifndef ALARA_CODE_MS5607_STRUCT_H
#define ALARA_CODE_MS5607_STRUCT_H

#include "Sensor_struct.h"

struct ms5607_struct : Sensor_struct {
    /**
     * Returns the formatted string for an MS5607 reading with the time, temperature, pressure, and altitude
     * @return Formatted reading of an MS5607 altitude
     */
    String toString() override;
    /**
     * Returns the CSV header for the MS5607 with the time, temperature, pressure, and altitude
     * @return CSV header for the MS5607
     */
    String getHeader() const override;
    /**
     * Constructor for an MS5607 reading
     * @param temperature Temperature recorded by the MS5607
     * @param pressure Barometric pressure recorded by the MS5607
     * @param altitude Calculated altitude generated by the MS5607
     */
    ms5607_struct(int32_t temperature, uint32_t pressure, uint32_t altitude);
    /**
     * Default constructor for an MS5607 struct
     */
    ms5607_struct() = default;
    /**
     * Temperature retrieved from sensor
     */
    int32_t temp{};
    /**
     * Pressure retrieved from sensor
     */
    uint32_t pres{};
    /**
     * Altitude from sensor altimeter
     */
    uint32_t alt{};
};


#endif //ALARA_CODE_MS5607_STRUCT_H
